#! /bin/bash

#################
# Git stuff
#################
alias team_prs="gh pr list --state open --label team-drive-science"

###############
# Root stuff
###############
alias cddevbox="cd ~/code/dev-box"
alias fix_fork_dbdo="OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES dbdo"
alias dbdo-dev-server="DBDO=true JOBS=false start-dev-server"
alias quick-dev-server="DBDO=false JOBS=false start-dev-server"
