# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

eval "$(pyenv init -)"

# bash git prompt
if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
  GIT_PROMPT_ONLY_IN_REPO=1
  source $HOME/.bash-git-prompt/gitprompt.sh
fi

PROMPT_USER_AND_HOST='\[\033[01;32m\]\u@\h'
PROMPT_PWD='\[\033[01;34m\]\w\[\033[00m\]'
GIT_PROMPT_START="${PROMPT_USER_AND_HOST}:${PROMPT_PWD}"
GIT_PROMPT_END=' $ '

# android
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export PATH=$PATH:$JAVA_HOME/bin
export ANDROID_HOME=$HOME/Android
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/tools/bin:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$PATH:$ANDROID_HOME/platform-tools
export ADB_SERVER_SOCKET=tcp:5037
alias windows_emulator="/mnt/b/Software/AndroidSdk/emulator/emulator.exe"
alias windows_adb="/mnt/b/Software/AndroidSdk/platform-tools/adb.exe"
alias windows_adb_start_server="windows_adb kill-server && windows_adb -a nodaemon server start"
alias windows_adb_start_socat="socat -d -d TCP-LISTEN:5037,reuseaddr,fork TCP:$(cat /etc/resolv.conf | tail -n1 | cut -d " " -f 2):5037"
alias windows_adb_start_device="windows_emulator @pixel2"
alias windows_adb_stop_server="windows_adb kill-server"
# BEGIN ANSIBLE MANAGED BLOCK
if [ -f "$HOME/.my_profile" ]; then
    . "$HOME/.my_profile"
fi
# END ANSIBLE MANAGED BLOCK
