#! /bin/bash

#################
# Rando stuff
#################
alias reset_personal="~/my_code/gh/fdm1/frank_dotfiles/activate.sh"
alias mkdir="mkdir -p"

#################
# Vim stuff
#################
alias vun=vim
alias vim=nvim
alias vi=nvim
alias viminit="vim ~/code/dev-box/dotfiles/nvim/init.vim"
alias vim_health="vim +CheckHealth"
alias vim_plug="vim +PlugInstall +PlugClean! +qall"


#################
# Git stuff
#################
alias gti=git
alias gs="git status"
alias gl="git log"
alias gd="git diff"
alias gds="git diff --staged"
alias gdno="git diff --name-only"
alias glo="git log --oneline"
alias ghist="git log --graph --abbrev-commit --pretty=format:'%C(red)%h%C(reset) - %s %C(green)(%cr) %C(blue)<%an>%C(magenta)%d%C(reset)' -20"
alias git_delete_local_branches="git branch | grep -v 'master\|release' | grep -v '*' | xargs git branch -D"
alias git_changed_files="git whatchanged --relative --name-only --pretty='' origin..HEAD | sort | uniq"
alias team_prs="gh pr list --state open --label team-drive-science"

function git_current_branch () {
  echo "$(git rev-parse --abbrev-ref HEAD)"
}

function git_force_push () {
  # TODO: make sure not on master or release
  git push -f origin $(git_current_branch)
}

function git_pull_current_branch() {
  git pull origin $(git_current_branch)
}


###############
# Rails/Ruby stuff
###############
function rspec_for_branch() {
  bundle exec rspec $(echo $(git_changed_files | grep _spec.rb))
}

function rubocop_for_branch() {
  bundle exec rubocop $(echo $(git_changed_files))
}


###############
# Root stuff
###############
alias cddevbox="cd ~/code/dev-box"
alias fix_fork_dbdo="OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES dbdo"
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# Parse a trip file and output start time, end time, and a Google Maps URL with the start and end location
function map () {
  aws s3 cp $1 - | zcat |\
  jq '.locations | first.timestamp |= todateiso8601 | last.timestamp |= todateiso8601 | "Start: \(first.timestamp)\nEnd: \(last.timestamp)\nhttps://google.com/maps/dir/\(first.latitude),\(first.longitude)/\(last.latitude),\(last.longitude)"' -r
}

# Log in to a Cognito Identity pool
function cognito-login() {
  aws_logout
  ID=$(aws cognito-identity get-id --identity-pool $1 | jq .'IdentityId' -r)
  CREDENTIALS_RESPONSE=$(aws cognito-identity get-credentials-for-identity --id $ID)
  AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS_RESPONSE | jq .'Credentials'.'AccessKeyId' -r)
  AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS_RESPONSE | jq .'Credentials'.'SecretKey' -r)
  AWS_SESSION_TOKEN=$(echo $CREDENTIALS_RESPONSE | jq .'Credentials'.'SessionToken' -r)
  echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
  echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
  echo "export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"
  export AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY
  export AWS_SESSION_TOKEN
  STS_IDENTITY_ARN=$(aws sts get-caller-identity | jq .'Arn')
  cat << EOF

Successfully exported the above variables and logged in as $STS_IDENTITY_ARN
EOF
}

. ~/code/root-infrastructure/sbin/tf-helpers.sh
