#! /bin/bash

function git_current_branch () {
  echo "$(git rev-parse --abbrev-ref HEAD)"
}

function git_force_push () {
  # TODO: make sure not on master or release
  git push -f origin $(git_current_branch)
}

function git_pull_current_branch() {
  git pull origin $(git_current_branch)
}


###############
# Rails/Ruby stuff
###############
function rspec_for_branch() {
  bundle exec rspec $(echo $(git_changed_files | grep _spec.rb))
}

function rubocop_for_branch() {
  bundle exec rubocop $(echo $(git_changed_files))
}


alias gh_cli=$(which gh)
function gh() {
  if [[ $(pwd) =~ $(echo ~)\/my_code ]]; then
    GITHUB_TOKEN=$PERSONAL_GH_CLI_TOKEN
  else
    GITHUB_TOKEN=$WORK_GH_CLI_TOKEN
  fi

  GITHUB_TOKEN=$GITHUB_TOKEN gh_cli $@
  unset GITHUB_TOKEN
}
