---
- name: Bash Config Setup | Add bin scripts to PATH
  blockinfile:
    path: ~/.my_profile
    marker: "# {mark} ANSIBLE - ADD {{ item }} BIN SCRIPTS TO PATH"
    block: |
      export PATH=$PATH:{{ dotfiles_base_dir }}/resources/bin_scripts/{{ item }}/
  with_items: "{{ systems_to_include }}"
