---
# TODO: Create base ~/.bash_profile if doesn't exist

- name: Bash Configs | Check if ~/.my_profile is sourced in ~/.bash_profile
  shell: grep -c ". ~/.my_profile" ~/.bash_profile || true
  register: my_profile_grep_result
  ignore_errors: true

- name: Bash Configs | Source ~/.my_profile in ~/.bash_profile
  blockinfile:
    path: ~/.bash_profile
    marker: "# {mark} ANSIBLE - SOURCE MY CONFIG"
    block: |
      if [ -f ~/.my_profile ]; then
          . ~/.my_profile
      fi
  when: my_profile_grep_result.stdout == "0"
