---
- name: Bash Config Setup | Find git files to symlink
  find:
    paths: "{{ dotfiles_base_dir }}/dotfiles/bash"
  register: find_bash_files
- name: Debug | Display bash files
  debug:
    msg: "bash_files: {{ find_bash_files.files }}"
- name: Bash Config Setup | Symlink all bash files
  file:
    force: true
    src: "{{ item.path }}"
    dest: "$HOME/.{{ item.path | basename }}"
    state: link
  with_items: "{{ find_bash_files.files }}"
