---
- name: Git Config Setup | Find git files to symlink
  find:
    paths: "{{ dotfiles_base_dir }}/dotfiles/git"
  register: find_git_files
- name: Debug | Display git files
  debug:
    msg: "git_files: {{ find_git_files.files }}"
- name: Git Config Setup | Symlink all git files
  file:
    force: true
    src: "{{ item.path }}"
    dest: "$HOME/.{{ item.path | basename }}"
    state: link
  with_items: "{{ find_git_files.files }}"
