---
# TODO: Create base ~/.gitconfig if doesn't exist

- name: Git Configs | Check if ~/.my_gitconfig is sourced in ~/.gitconfig
  shell: grep -c "path = ~/.my_gitconfig" ~/.gitconfig || true
  register: my_gitconfig_grep_result
  ignore_errors: true

- name: Git Configs | Source ~/.my_gitconfig in ~/.gitconfig
  blockinfile:
    path: ~/.gitconfig
    marker: "# {mark} ANSIBLE - SOURCE MY CONFIG"
    block: |
      [include]
        path = ~/.my_gitconfig
  when: my_gitconfig_grep_result.stdout == "0"
