---
# TODO: Create base ~/.config/nvim/init.vim if doesn't exist

- name: Nvim Configs | Check if ~/.my_nvimrc is sourced in ~/.config/nvim/init.vim
  shell: grep -c 'if filereadable(expand("~/.my_nvimrc"))' ~/.config/nvim/init.vim || true
  register: my_nvimrc_grep_result
  ignore_errors: true

- name: Nvim Configs | Source ~/.my_nvimrc in ~/.config/nvim/init.vim
  blockinfile:
    path: ~/.config/nvim/init.vim
    marker: "\" {mark} ANSIBLE - SOURCE MY CONFIG"
    block: |
      if filereadable(expand("~/.my_nvimrc"))
        source $HOME/.my_nvimrc
      endif
  when: my_nvimrc_grep_result.stdout == "0"
