---
- name: Config Files | Load tasks to source my configs
  include_tasks: "config_files/source_my_configs.yml"
  vars:
    name: "{{ item.name }}"
    config_file: "{{ item.config_file }}"
    my_config_file: "{{ item.my_config_file }}"
    comment_char: "{{ item.comment_char }}"
    grep_string: "{{ item.grep_string }}"
    config_block: "{{ item.config_block }}"

  with_items:
    - name: Bash
      config_file: ~/.bash_profile
      my_config_file: ~/.my_profile
      comment_char: "#"
      config_block: |
        if [ -f ~/.my_profile ]; then
            . ~/.my_profile
        fi
    - name: Git
      config_file: ~/.gitconfig
      my_config_file: ~/.my_gitconfig
      comment_char: "#"
      config_block: |
        [include]
          path = ~/.my_gitconfig
    - name: Nvim
      config_file: ~/.config/nvim/init.vim
      my_config_file: ~/.my_nvimrc
      comment_char: "\""
      config_block: |
        if filereadable(expand("~/.my_nvimrc"))
          source $HOME/.my_nvimrc
        endif
    - name: Tmux
      config_file: ~/.tmux.conf
      my_config_file: ~/.my_tmux.conf
      comment_char: "#"
      config_block: |
        if-shell 'test -f ~/.my_tmux.conf' 'source ~/.my_tmux.conf'

- name: Config Files | Load tasks for specifc config tasks
  include_tasks: "config_files/{{ item }}.yml"
  with_items:
  - bash
  - git
  - tmux
  - nvim
