---
- name: Symlink tmux files
  include_tasks: config_files/symlink_files.yml
  vars:
    config_type: tmux
    dest_prefix: "."

- name: Symlink nvim files
  include_tasks: config_files/symlink_files.yml
  vars:
    config_type: nvim
    dest_prefix: ".config/nvim/"

- name: Symlink bash files
  include_tasks: config_files/symlink_files.yml
  vars:
    config_type: bash
    dest_prefix: "."

- name: Symlink git files
  include_tasks: config_files/symlink_files.yml
  vars:
    config_type: git
    dest_prefix: "."

- name: Config Files | Load tasks for specifc config tasks
  include_tasks: "config_files/{{ specific_config_item }}.yml"
  loop:
  - nvim
  loop_control:
    loop_var: specific_config_item
