---
- name: Tmux Config Setup | Source system-specific tmux configs
  blockinfile:
    path: ~/.my_tmux.conf
    marker: "# {mark} ANSIBLE - SOURCE tmux.conf FOR {{ tmux_item }}"
    block: |
      if-shell 'test -f {{ dotfiles_base_dir }}/resources/tmux/{{ tmux_item }}/tmux.conf' 'source {{ dotfiles_base_dir }}/resources/tmux/{{ tmux_item }}/tmux.conf'
  loop: "{{ systems_to_include }}"
  loop_control:
    loop_var: tmux_item
