---
# TODO: Create base ~/.bash_profile if doesn't exist

- name: Bash | Check if ~/.my_profile is sourced in ~/.bash_profile
  # TODO: This grepping fails...
  shell: grep -c ". \$HOME/.my_profile" ~/.bash_profile
  register: my_profile_grep_result
  ignore_errors: true

- name: Bash | Source ~/.my_profile in ~/.bash_profile
  blockinfile:
    path: ~/.bash_profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      if [ -f "$HOME/.my_profile" ]; then
          . "$HOME/.my_profile"
      fi
  when: not my_profile_grep_result.rc == 0
