---
# TODO: Create base ~/.gitconfig if doesn't exist

- name: Git | Check if ~/.my_gitconfig is sourced in ~/.gitconfig
  shell: grep -c "path = ~/.my_gitconfig" ~/.gitconfig
  register: my_gitconfig_grep_result
  ignore_errors: true

- name: Git | Source ~/.my_gitconfig in ~/.gitconfig
  blockinfile:
    path: ~/.gitconfig
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      [include]
        path = ~/.my_gitconfig
  when: not my_gitconfig_grep_result.rc == 0
