---

- name: Packages | Update homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Packages | Brew install things
  homebrew:
    name: "{{ homebrew_packages }}"
    state: latest

