---
- name: install rbenv
  homebrew:
    name:
      - rbenv
      - ruby-build
    state: present
    update_homebrew: True
  register: install_rbenv
- name: update homebrew for latest rbenv ruby-build
  homebrew:
    name:
      - rbenv
      - ruby-build
    state: latest
    update_homebrew: True
  register: brew_update_rbenv

- name: run rbenv rehash when ruby or rbenv has updated
  shell: rbenv rehash
  when: install_rbenv.changed or brew_update_rbenv.changed

# - name: Install ruby versions and ruby packages
#   shell: |
#     RUBY_CONFIGURE_OPTS="--with-readline-dir=$(brew --prefix readline)" rbenv install --skip-existing {{ item['ruby'] }}
#     RBENV_VERSION={{ item['ruby'] }} ~/.rbenv/shims/gem install bundler --version {{ item['bundler'] }}
#   with_items: "{{ ruby_versions }}"