---
- name: Fact Gathering | Set OS distribution fact
  set_fact:
    os: "{{ ansible_distribution|lower }}"

- name: Fact Gathering | Initialize systems_to_include fact
  set_fact:
    systems_to_include: "{{ [os] }}"

- name: Fact Gathering | Register root repo directory
  command: pwd
  register: ansible_dir_cmd

- name: Fact Gathering | Set root_dir fact
  set_fact:
    dotfiles_base_dir: "{{ ansible_dir_cmd.stdout.split('/')[:-1] | join('/') }}"

- name: Fact Gathering | Check if using WSL
  command: which wsl.exe
  register: wsl_check_cmd
  ignore_errors: true

- name: Fact Gathering | Add WSL to systems_to_include if WSL
  set_fact:
    systems_to_include: "{{ systems_to_include + ['wsl'] }}"
  when: wsl_check_cmd.rc == 0


- name: Fact Gathering | Check if personal macbook
  stat:
    path: ~/.is_macosx_personal
  register: is_macosx_personal

- name: Fact Gathering | Add macosx-personal to systems_to_include if personal macbook
  set_fact:
    systems_to_include: "{{ systems_to_include + ['macosx-personal'] }}"
  when: is_macosx_personal.stat.exists

- name: Fact Gathering | Check if root work computer
  stat:
    path: ~/.is_macosx_root
  register: is_macosx_root

- name: Fact Gathering | Add macosx-root to systems_to_include if root work computer
  set_fact:
    systems_to_include: "{{ systems_to_include + ['macosx-root'] }}"
  when: is_macosx_root.stat.exists

- name: Fact Gathering | Display OS
  debug:
    msg: "os: {{ os }}"

- name: Fact Gathering | Dotfiles base dir
  debug:
    msg: "dotfiles_base_dir: {{ dotfiles_base_dir }}"

- name: Fact Gathering | Display systems_to_include
  debug:
    msg: "systems_to_include: {{ systems_to_include }}"
