---
- name: Setup | Setup playbook
  hosts: all
  tasks:
  - name: Config Files | Ensure .config directory exists
    file:
      path: "{{ config_dir }}"
      state: directory
  - name: Config Files | Symlink home dir dotfiles
    include_tasks: symlink_home_files.yml
    vars:
      config_type: "{{ config_item.config_type }}"
    loop:
      - config_type: bash
      - config_type: tmux
      - config_type: git
    loop_control:
      loop_var: config_item

  - include_tasks: nvim.yml
  - include_tasks: ruby.yml
  - include_tasks: install_other_packages.yml