---
# TODO: Create base ~/.tmux.conf if doesn't exist

- name: Tmux | Check if ~/.my_tmux.conf is sourced in ~/.tmux.conf
  shell: grep -c "source ~/.my_tmux.conf" ~/.tmux.conf
  register: my_tmux_conf_grep_result
  ignore_errors: true

- name: Tmux | Source ~/.my_tmux.conf in ~/.tmux.conf
  blockinfile:
    path: ~/.tmux.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      if-shell 'test -f ~/.my_tmux.conf' 'source ~/.my_tmux.conf'
  when: not my_tmux_conf_grep_result.rc == 0
