#! /bin/bash

#################
# Rando stuff
#################
alias mkdir="mkdir -p"
alias ls="ls -G"
alias l="ls -lFh"
alias la='ls -a'
alias ll='ls -alh'
alias grep='grep --color'
alias gcloud_ssh="gcloud alpha cloud-shell ssh --ssh-flag=-A"
alias ports_in_use="sudo lsof -i -P | grep LISTEN"

#################
# Vim stuff
#################
alias vun=vim
alias vim=nvim
alias vi=nvim
alias viminit="vim ~/code/fdm1/frank_dotfiles/config/nvim/init.vim"
alias vim_health="vim +checkhealth"
alias vim_plug_install="vim +PlugInstall +PlugClean! +UpdateRemotePlugins +qall"
alias vim_plug_update="vim +PlugUpdate +PlugClean! +qall"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim.sock nvim"
alias pry_neovim="pry -e \"require 'neovim'; client = Neovim.attach_unix('/tmp/nvim.sock')\""GG

#################
# Git stuff
#################
alias gs="git status"
alias gl="git log"
alias gd="git diff"
alias gds="git diff --staged"
alias g="git"
alias gt="git status"
alias gb="git branch -vv"
alias gd="git diff"
alias gdno="git diff --name-only"
alias gca="git commit --all"
alias gcw="git commit -t <(cat $(git config commit.template) <(echo) <(echo) <(gitcoauthoredby))"
alias gitopen='vim $(git status -s | awk '"'"'{print $2}'"'"')'
alias gr="git reset"
alias gs="git status"
alias gl="git log"
alias glo="git log --oneline"
alias gti=git
alias gs="git status"
alias gl="git log"
alias gd="git diff"
alias gds="git diff --staged"
alias gdno="git diff --name-only"
alias glo="git log --oneline"
alias ghist="git log --graph --abbrev-commit --pretty=format:'%C(red)%h%C(reset) - %s %C(green)(%cr) %C(blue)<%an>%C(magenta)%d%C(reset)' -20"
alias git_delete_local_branches="git branch | grep -v 'master\|release\|main' | grep -v '\*' | xargs git branch -D"
alias git_changed_files="git diff --diff-filter=d --name-only --relative origin..HEAD | sort | uniq"
alias git_changed_files_and_local="{ git_changed_files & git diff --diff-filter=d --name-only --relative HEAD; } | sort | uniq"

alias be="bundle exec"
alias bi="bundle install"
alias emulator='$ANDROID_HOME/emulator/emulator'
alias openandroidstudio="aws-login eng && open /Applications/Android\ Studio.app"
alias openintellijidea="aws-login eng && open /Applications/IntelliJ\ IDEA.app"
alias rc="bundle exec rails c"
alias iterm_scripts="cd $HOME/Library/Application\ Support/iTerm2/Scripts"
