export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)

zstyle ':completion:*:*:git:*' script ~/.shell_completion/git-completion.bash
fpath=(~/.zsh $fpath)

autoload -Uz compinit && compinit

source $ZSH/oh-my-zsh.sh
source $HOME/.bash_profile
