#! /bin/bash

#################
# WSL memory management
#################
alias drop_cache="sudo sh -c \"echo 3 >'/proc/sys/vm/drop_caches' && swapoff -a && swapon -a && printf '\n%s\n' 'Ram-cache and Swap Cleared'\""

#################
# WSL android <> windows
#################
alias windows_emulator="/mnt/b/Software/AndroidSdk/emulator/emulator.exe"
alias windows_adb="/mnt/b/Software/AndroidSdk/platform-tools/adb.exe"
alias windows_adb_start_server="windows_adb kill-server && windows_adb -a nodaemon server start"
alias windows_adb_start_socat="socat -d -d TCP-LISTEN:5037,reuseaddr,fork TCP:$(cat /etc/resolv.conf | tail -n1 | cut -d " " -f 2):5037"
alias windows_adb_start_device="windows_emulator @pixel2"
alias windows_adb_stop_server="windows_adb kill-server"
